space-plugins/nuxt-base/middleware/persist-query.global.ts

This PR adds a [middleware](https://nuxt.com/docs/guide/directory-structure/middleware) to the nuxt-base project, which makes sure that essential query parameters are preserved throughout navigation. 
In this case the query parameters that must be preserved are:
- space_id | spaceId
- user_id | userId
(everything else is optional for the time being)
Preserving of the query parameters is important as it is used to retrieve the correct session from cookies (see `getAppSession.ts` inside nuxt-base)
[JIRA: EXT-2218](https://storyblok.atlassian.net/browse/EXT-2218)
1. Locally, create a new page such as `/settings`
2. Open the settings page and inspect it's URL
3. See if the query parameters were correctly preserved

feat(common): persist query parameters

---

.github/dependabot.yml

This PR adds dependabot configuration. As this repository may be one of our most active repositories, it'd be nice to have the same configuration as field-plugin repository.

chore(common): add dependabot

---

space-plugins/nuxt-base/app.config.ts
space-plugins/nuxt-base/server/middleware/02.auth.global.ts

Adding new option `disabledMiddlewarePaths` to have a possibility to disable middleware for specific paths. 
JIRA: EXT-2300
1. Inside `space-plugin/nuxt-starter/nuxt.config.ts` replace the `extends` property to use the local nuxt base (`extends: [['../nuxt-base', { install: true }]]` )
2. Create a new endpoint inside the `nuxt-starter` (e.g: `api/disabled`)
3. Create a new file inside `nuxt-starter` with the file name `app.config.ts` with the following content: 
```
export default defineAppConfig({
auth: {
disabledMiddlewarePaths: ['api/disabled'],
},
});
```
4. Place a console.log inside `nuxt-base/server/middleware/02.auth.global.ts` on line 11, to verify if the disabled function works correctly
5. Run `pnpm run dev`
6. Hit the `api/disabled` endpoint and observe if the console log was …

feat(common): add disabledMiddlewarePaths option to app.config.ts

---

space-plugins/nuxt-starter/README.md
tool-plugins/nextjs-starter/README.md

- Fix some bash commands
- Include a Getting Started section with the `npx command` for the Tool Starter 
As I was following the internal onboarding and I found this useful, I wanted to add it here 💜

docs(common): include the getting started npx command for Tool Starter

---

space-plugins/nuxt-base-ui/.eslintrc.cjs
space-plugins/nuxt-base-ui/.gitignore
space-plugins/nuxt-base-ui/.npmrc
space-plugins/nuxt-base-ui/.nuxtrc
space-plugins/nuxt-base-ui/.playground/app.config.ts
space-plugins/nuxt-base-ui/.playground/app.vue
space-plugins/nuxt-base-ui/.playground/nuxt.config.ts
space-plugins/nuxt-base-ui/README.md
space-plugins/nuxt-base-ui/app.config.ts
space-plugins/nuxt-base-ui/components/BaseAlert.vue
space-plugins/nuxt-base-ui/composables/useAlert.ts
space-plugins/nuxt-base-ui/nuxt.config.ts
space-plugins/nuxt-base-ui/package.json
space-plugins/nuxt-base-ui/plugins/base-error-handler.ts
space-plugins/nuxt-base-ui/pnpm-lock.yaml
space-plugins/nuxt-base-ui/tsconfig.json
space-plugins/nuxt-base-ui/types/alert.ts
space-plugins/nuxt-starter/nuxt.config.ts
space-plugins/nuxt-starter/pages/index.vue
space-plugins/nuxt-starter/tailwind.config.js

- New layer: `nuxt-base-ui` for components, composables, plugins, and everything related to the UI
- Add an Alert component, plugin, and a composable used as an abstraction of the inject functionality
To share the alert components and error handling among plugins.
Use the new layer locally with the relative path or in the playground.

feat(common): add nuxt-base-ui layer with an Alert functionality

---

space-plugins/nuxt-base-ui/.playground/app.vue
space-plugins/nuxt-base-ui/components/BaseModal.vue

This PR includes a BaseModal component to be able to reuse across Plugins.
This is how it looks:
JIRA: EXT-2901
By changing `'github:storyblok/space-tool-plugins/space-plugins/nuxt-base-ui',` with `../nuxt-base-ui` in Nuxt-Starter nuxt.config.ts file, you will be able to try out the same code at the playground with the applied styles by Daisy.

feat(common): include a BaseModal component and a usage example

---

space-plugins/nuxt-starter/nuxt.config.ts

This PR updates google fonts config to use roboto 500
We've been trying to use weight 500, but it didn't work due to the lack of this configuration.

fix(common): update google fonts config to use roboto 500

---

space-plugins/nuxt-base-ui/plugins/base-error-handler.ts

In `nuxt-base-ui`, we show an alert on errors. So far we only take care of `FetchError`, but this PR adds support for `NuxtError`.
Before this PR, if you `throw createError({ statusCode: xxx, statusMessage: '...' })`, it still showed 'Unknown error'. Now it will display proper error message given from the `createError()` call.

feat(common): handle NuxtError

---

space-plugins/nuxt-base/server/utils/webhook.ts

- Fixes the problem with typescript
- If err.data is available we can pass it to the end-consumer
While I was testing a webhook issue occurring on the community plan, the integration only received an 'unknown' error. After exploring the error object I found out that in my case error.data provided more information on why the problem is happening. That is why I believe it will be a great addition.

feat(space-nuxt-base): fix webhook error message to provide more context

---

space-plugins/nuxt-base-ui/plugins/base-error-handler.ts

This PR shows unhandled error by `showError()`.
https://github.com/storyblok/space-tool-plugins/assets/499898/e757b0dc-bfee-4876-b6d7-772232e9df89

fix(space-nuxt-base-ui): show unhandled error

---

space-plugins/nuxt-base-ui/package.json
space-plugins/nuxt-base-ui/pnpm-lock.yaml
space-plugins/nuxt-base/package.json
space-plugins/nuxt-base/pnpm-lock.yaml
space-plugins/nuxt-starter/package.json
space-plugins/nuxt-starter/pnpm-lock.yaml

Downgrade Nuxt to 3.11.1 due to an error on parsing queries in Vercel/Netlify.

fix(space-nuxt-base-ui): downgrade due to Vercel parsing query params problem

---

space-plugins/nuxt-base/server/middleware/02.auth.global.ts

- Removing functionality to reset the session cookie. This logic should be handled by app-extension-auth library. 
- Add forwarding of `init_oauth` query parameter.
This problem and solution are necessary as there is no way to remove the cookies when a plugin is uninstalled. This can cause issues when a plugin is reinstalled as the old cookie is persisted. When app-extension-auth finds that there is a cookie, it will try to use it, even when it is not valid anymore.
JIRA: SHAPE-5947
This PR depends and can only be merged after [#38](https://github.com/storyblok/app-extension-auth/pull/38) is merged and a new version of app-extension-auth is released.

feat(space-nuxt-base): remove init_oauth stale cookie deletion and move to app-extension-auth

---

space-plugins/nuxt-base/package.json
space-plugins/nuxt-base/pnpm-lock.yaml
space-plugins/nuxt-base/server/middleware/02.auth.global.ts
space-plugins/nuxt-base/server/utils/getAppSession.ts

This PR upgrads app-extension-auth to v2.

fix(space-nuxt-base): upgrade app-extension-auth

---

space-plugins/nuxt-base/composables/useAppBridge.ts
space-plugins/nuxt-base/layouts/default.vue
space-plugins/nuxt-base/server/middleware/02.app_bridge.global.ts
space-plugins/nuxt-base/server/middleware/03.oauth.global.ts
space-plugins/nuxt-base/server/middleware/04.app_session.global.ts
space-plugins/nuxt-base/types/appBridge.ts

This PR refactors `useAppBridge()` for better maintainability.
It's a bit hard to diff the code, because I moved things around.
One notable change is that I added a param `authenticated()` to `useAppBridgeAuth({ authenticated })`, so that I can initiate oauth flow right after finishing app bridge auth flow.

fix(space-nuxt-base): refactor useAppBridge()

---

space-plugins/nuxt-base/app.config.ts
space-plugins/nuxt-base/composables/useAppBridge.ts
space-plugins/nuxt-base/server/middleware/01.handle-401.global.ts
space-plugins/nuxt-base/server/middleware/04.app_session.global.ts
space-plugins/nuxt-base/types/appBridge.ts

This PR moves the plugin type to the top level of appConfig.
This way, we can differentiate if the project is a tool plugin or a space plugin no matter if it's using app bridge or not. It's not necessary right now, but with this, we could easily create a starter for Tool Plugins based on this nuxt-base project. Only difference between Space Plugins and Tool Plugins is that Tool Plugins should send its height to Storyfront. We can do it by updating the layout file within Tool Plugins' starter project.

fix(space-nuxt-base): move plugin type to the top level of app config

---

space-plugins/nuxt-base/package.json
space-plugins/nuxt-base/pnpm-lock.yaml
space-plugins/nuxt-starter/layouts/default.vue
space-plugins/nuxt-starter/package.json
space-plugins/nuxt-starter/pnpm-lock.yaml
space-plugins/story-starter/pnpm-lock.yaml
space-plugins/story-starter/starters/nuxt/package.json

This PR moves `layouts/default.vue` from nuxt-base to nuxt-starter. If user has their own `layouts/default.vue`, then it will override the one from nuxt-base. To avoid this, we should just put the layout in the starter project, so that user can directly update the layout file as they want.

fix(space-nuxt-starter): move default layout to nuxt-starter

---

space-plugins/nuxt-base/server/middleware/02.app_bridge.global.ts

Although it's correctly auto-imported, Nuxt is failing to resolve it. So let's explicitly import this.

fix(space-nuxt-base): explicitly import

---

space-plugins/nuxt-base/composables/useAppBridge.ts
space-plugins/nuxt-base/utils/appBridge.ts
space-plugins/nuxt-starter/index.d.ts
space-plugins/nuxt-starter/layouts/default.vue
space-plugins/story-starter/starters/nuxt/index.d.ts
tool-plugins/nuxt-starter/app.config.ts
tool-plugins/nuxt-starter/composables/useAutoHeight.ts
tool-plugins/nuxt-starter/composables/useStoryContext.ts
tool-plugins/nuxt-starter/index.d.ts
tool-plugins/nuxt-starter/layouts/default.vue
tool-plugins/nuxt-starter/pages/index.vue
tool-plugins/nuxt-starter/pnpm-lock.yaml
tool-plugins/nuxt-starter/types/storyContext.ts

This PR
- adds `useAutoHeight()` and `useStoryContext()` composables
- fix types

fix(tool-nuxt): add composables and fix types

---

space-plugins/nuxt-base/composables/useAppBridge.ts
space-plugins/nuxt-base/index.d.ts
space-plugins/nuxt-base/server/middleware/02.app_bridge.global.ts
space-plugins/nuxt-base/server/utils/appBridge.ts
space-plugins/nuxt-base/types/appBridge.ts

This PR updates the app bridge middleware to add `appBridgeSession` to `event.context` when app bridge authentication is successful.
There are ways to get spaceId on the server side. We could explicitly include spaceId in http requests but it's tedious. If we're using OAuth, we could get it via `event.context.appSession`. However, we don't have such thing for App Bridge. In case a project is using App Bridge only without OAuth, we need something like `event.context.appBridgeSession` to get the authenticated session information on the server side.

feat(space-nuxt-base): add appBridgeSession

---

.github/pull_request_template.md
.github/workflows/ci-next-templates.yml
README.md
space-plugins/nextjs-starter/README.md
space-plugins/nextjs-starter/package.json
space-plugins/nextjs-starter/pnpm-lock.yaml
tool-plugins/nextjs-starter/README.md
tool-plugins/nextjs-starter/package.json
tool-plugins/nextjs-starter/yarn.lock

Issue: SHAPE-9348
- Update `nextjs-starter` space & tool plugins dependencies (not Next or React to avoid compatibility issues).
- Improve docs details.
- Add a CI workflow for `nextjs` projects.
To keep the templates updated and have a way for the future to check the build is not breaking during the PR review.

chore(tool-next, space-next): update dependencies, docs and add a CI GitHub Action for Nextjs starters

---

space-plugins/nextjs-starter/package.json
space-plugins/nextjs-starter/pnpm-lock.yaml
space-plugins/nuxt-base/package.json
space-plugins/nuxt-base/pnpm-lock.yaml
space-plugins/nuxt-starter/package.json
space-plugins/nuxt-starter/pnpm-lock.yaml
space-plugins/nuxt-story-starter/package.json
space-plugins/nuxt-story-starter/pnpm-lock.yaml
tool-plugins/nextjs-starter/package.json
tool-plugins/nextjs-starter/yarn.lock
tool-plugins/nuxt-starter/package.json
tool-plugins/nuxt-starter/pnpm-lock.yaml

Jira ticket: [SHAPE-9631](https://storyblok.atlassian.net/browse/SHAPE-9631)
It updates the [region-helper](https://www.npmjs.com/package/@storyblok/region-helper) and [app-extension-auth](https://www.npmjs.com/package/@storyblok/app-extension-auth) packages to their latest version.
So it is ready to work with the new [SpaceId](https://github.com/storyblok/region-helper/pull/18) (using BigInt) when it is fully released.
If you need an example of how to test plugins locally, please go to this PR, where I added a new doc about it => https://github.com/storyblok/storyfront/pull/7570
[SHAPE-9631]: https://storyblok.atlassian.net/browse/SHAPE-9631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(common): update all instances of auth-extension + region helper to the latest version

---

space-plugins/nuxt-base/server/middleware/02.app_bridge.global.ts
space-plugins/nuxt-base/server/utils/webhook.ts

Issue: SHAPE-10323, SHAPE-9203
- Change the webhook limit-exceed error checking. 
- Skip App bridge for routes configured in the [ignoredPaths](https://github.com/storyblok/space-tool-plugins/blob/cf6a1e654a37c43b21949906fee3bd25dbed54df/space-plugins/nuxt-base/utils/authConfig.ts#L13).
So it better logs the error and provides more insights to the users, and avoids breaking API calls that don't require the user to be authenticated.

fix(space-nuxt-base): webhook limit reached handling
